--
-- ER/Studio Data Architect SQL Code Generation
-- Project :      DATA MODEL
--
-- Date Created : Tuesday, May 29, 2018 14:00:09
-- Target DBMS : MySQL 5.x
--

-- 
-- TABLE: ADDRESSES 
--

CREATE TABLE ADDRESSES(
    ADDRESSID    CHAR(10)    NOT NULL,
    PRIMARY KEY (ADDRESSID)
)ENGINE=MYISAM
;



-- 
-- TABLE: CUSTOMERS 
--

CREATE TABLE CUSTOMERS(
    CUSTOMERID       CHAR(10)    NOT NULL,
    NAME             CHAR(10),
    EMAIL_ADDRESS    CHAR(10),
    PRIMARY KEY (CUSTOMERID)
)ENGINE=MYISAM
;



-- 
-- TABLE: ORDER_ADDRESSES 
--

CREATE TABLE ORDER_ADDRESSES(
    ORDER_ADDRESS_TYPE    CHAR(10)    NOT NULL,
    ORDERID               CHAR(10)    NOT NULL,
    CUSTOMERID            CHAR(10)    NOT NULL,
    ADDRESSID             CHAR(10)    NOT NULL,
    PRIMARY KEY (ORDER_ADDRESS_TYPE, ORDERID, CUSTOMERID, ADDRESSID)
)ENGINE=MYISAM
;



-- 
-- TABLE: ORDER_PAYMENTS 
--

CREATE TABLE ORDER_PAYMENTS(
    ORDERID           CHAR(10)    NOT NULL,
    CUSTOMERID        CHAR(10)    NOT NULL,
    ACCOUNT_NUMBER    CHAR(10)    NOT NULL,
    PRIMARY KEY (ORDERID, CUSTOMERID, ACCOUNT_NUMBER)
)ENGINE=MYISAM
;



-- 
-- TABLE: ORDER_PRODUCT_ITEMS 
--

CREATE TABLE ORDER_PRODUCT_ITEMS(
    ORDERID       CHAR(10)    NOT NULL,
    CUSTOMERID    CHAR(10)    NOT NULL,
    SKU           CHAR(10)    NOT NULL,
    QUANTITY      INT         NOT NULL,
    PRIMARY KEY (ORDERID, CUSTOMERID, SKU)
)ENGINE=MYISAM
;



-- 
-- TABLE: ORDERS 
--

CREATE TABLE ORDERS(
    ORDERID                CHAR(10)    NOT NULL,
    CUSTOMERID             CHAR(10)    NOT NULL,
    ORDER_DATE             CHAR(10),
    PROJECTED_SHIP_DATE    CHAR(10),
    ACTUAL_SHIP_DATE       CHAR(10),
    PRIMARY KEY (ORDERID, CUSTOMERID)
)ENGINE=MYISAM
;



-- 
-- TABLE: PAYMENT_METHODS 
--

CREATE TABLE PAYMENT_METHODS(
    ACCOUNT_NUMBER    CHAR(10)    NOT NULL,
    ACCOUNT_TYPE      CHAR(10),
    PRIMARY KEY (ACCOUNT_NUMBER)
)ENGINE=MYISAM
;



-- 
-- TABLE: PRODUCTS 
--

CREATE TABLE PRODUCTS(
    SKU               CHAR(10)          NOT NULL,
    PRODUCT_NAME      CHAR(10)          NOT NULL,
    COST              DECIMAL(10, 2)    NOT NULL,
    PRICE             DECIMAL(10, 2),
    EFFECTIVE_DATE    CHAR(10),
    PRIMARY KEY (SKU)
)ENGINE=MYISAM
;



-- 
-- TABLE: ORDER_ADDRESSES 
--

ALTER TABLE ORDER_ADDRESSES ADD CONSTRAINT RefORDERS8 
    FOREIGN KEY (ORDERID, CUSTOMERID)
    REFERENCES ORDERS(ORDERID, CUSTOMERID) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE ORDER_ADDRESSES ADD CONSTRAINT RefADDRESSES9 
    FOREIGN KEY (ADDRESSID)
    REFERENCES ADDRESSES(ADDRESSID) ON DELETE RESTRICT ON UPDATE RESTRICT
;


-- 
-- TABLE: ORDER_PAYMENTS 
--

ALTER TABLE ORDER_PAYMENTS ADD CONSTRAINT RefORDERS10 
    FOREIGN KEY (ORDERID, CUSTOMERID)
    REFERENCES ORDERS(ORDERID, CUSTOMERID) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE ORDER_PAYMENTS ADD CONSTRAINT RefPAYMENT_METHODS11 
    FOREIGN KEY (ACCOUNT_NUMBER)
    REFERENCES PAYMENT_METHODS(ACCOUNT_NUMBER) ON DELETE RESTRICT ON UPDATE RESTRICT
;


-- 
-- TABLE: ORDER_PRODUCT_ITEMS 
--

ALTER TABLE ORDER_PRODUCT_ITEMS ADD CONSTRAINT RefORDERS6 
    FOREIGN KEY (ORDERID, CUSTOMERID)
    REFERENCES ORDERS(ORDERID, CUSTOMERID) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE ORDER_PRODUCT_ITEMS ADD CONSTRAINT RefPRODUCTS7 
    FOREIGN KEY (SKU)
    REFERENCES PRODUCTS(SKU) ON DELETE RESTRICT ON UPDATE RESTRICT
;


-- 
-- TABLE: ORDERS 
--

ALTER TABLE ORDERS ADD CONSTRAINT RefCUSTOMERS2 
    FOREIGN KEY (CUSTOMERID)
    REFERENCES CUSTOMERS(CUSTOMERID) ON DELETE RESTRICT ON UPDATE RESTRICT
;


